[package]
name = "action"
version = "0.0.6"
edition = "2021"
publish = false

[[bin]]
name = "publish-crates-action"
path = "src/main.rs"

[dependencies]
publish-crates = { path = "../" }
duration-string = "0"
tokio = { version = "1", features = ["full"] }
color-eyre = "0.6"
actions-toolkit = "0"
