# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

dist: goreleaser-dist

before:
  hooks:
    - rustup default stable
    - cargo install --locked --force cargo-zigbuild

brews:
  - name: cargo-publish-crates
    ids:
      - cargo-publish-crates
    description: "Publish rust crates with support for cargo workspaces"
    directory: Formula
    commit_author:
      name: romnn
      email: contact@romnn.com
    repository:
      owner: romnn
      name: homebrew-tap
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      pull_request:
        enabled: false

builds:
  # cargo-publish-crates binary
  - id: "cargo-publish-crates"
    builder: rust
    binary: cargo-publish-crates
    # see: https://doc.rust-lang.org/nightly/rustc/platform-support.html
    targets:
      # linux
      - x86_64-unknown-linux-musl
      - aarch64-unknown-linux-musl
      # macos
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      # windows
      - x86_64-pc-windows-gnu
      - aarch64-pc-windows-gnullvm
    dir: ./
    tool: cargo
    command: zigbuild
    flags:
      - "--release"
      - "--package=cargo-publish-crates"
      - "--bin=cargo-publish-crates"
      - "--target-dir=./target" # TODO: can we remove this once rust support is better?

  # publish-crates-action binary
  - id: "publish-crates-action"
    builder: rust
    binary: publish-crates-action
    # see: https://doc.rust-lang.org/nightly/rustc/platform-support.html
    targets:
      # linux
      - x86_64-unknown-linux-musl
      - aarch64-unknown-linux-musl
      # macos
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      # windows
      - x86_64-pc-windows-gnu
      - aarch64-pc-windows-gnullvm
    dir: ./
    tool: cargo
    command: zigbuild
    flags:
      - "--release"
      - "--package=publish-crates-action"
      - "--bin=publish-crates-action"
      - "--target-dir=./target" # TODO: can we remove this once rust support is better?

archives:
  - id: cargo-publish-crates
    formats: ["tar.gz"]
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    ids:
      - cargo-publish-crates
    files:
      - LICENSE
    format_overrides:
      - goos: windows
        formats: ["zip"]
  - id: publish-crates-action
    formats: ["tar.gz"]
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    ids:
      - publish-crates-action
    files:
      - LICENSE
    format_overrides:
      - goos: windows
        formats: ["zip"]

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  filters:
    exclude:
      - "^ci:"
      - "^docs:"
      - "^test:"

release:
  draft: false
