name: publish crates
description: Publish crates on crates.io
author: romnn <contact@romnn.com>
branding:
  icon: box
  color: orange
inputs:
  version:
    description: Version of the tool (defaults to the version of the action)
  token:
    description: Github API token
    default: ${{ github.token }}
  path:
    description: Path to package or workspace
    default: .
  include:
    description: Packages that should be published
  exclude:
    description: Packages that should not be published
  extra-args:
    description: Additional arguments for cargo publish
  registry-token:
    description: Cargo registry token (e.g. crates.io)
  dry-run:
    description: This will perform all checks without publishing the package
    default: "false"
  publish-delay:
    description: Delay before attempting to publish dependent crate
  no-verify:
    description: Disable pre-publish validation checks
    default: "false"
  resolve-versions:
    description: Resolve missing versions for local packages
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Install publish-crates-action
      uses: romnn/action-release-download@main
      with:
        version: "latest"
        repo: romnn/publish-crates
        # prettier-ignore
        assets: |
          - >-
            *publish-crates-action*
            {{~#switch platform ~}}
              {{~#case "win32"~}}windows{{~/case~}}
              {{~#default~}}{{~platform~}}{{~/default~}}
            {{~/switch~}}
            _
            {{~#switch arch ~}}
            {{~#case "x64"~}}amd64{{~/case~}}
            {{~#default~}}{{~arch~}}{{~/default~}}
            {{~/switch~}}
            *
    - name: Publish crates
      shell: bash
      run: publish-crates-action
      env:
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_PATH: ${{ inputs.path }}
        INPUT_INCLUDE: ${{ inputs.include }}
        INPUT_EXCLUDE: ${{ inputs.exclude }}
        INPUT_EXTRA-ARGS: ${{ inputs.extra-args }}
        INPUT_REGISTRY-TOKEN: ${{ inputs.registry-token }}
        INPUT_DRY-RUN: ${{ inputs.dry-run }}
        INPUT_PUBLISH-DELAY: ${{ inputs.publish-delay }}
        INPUT_NO-VERIFY: ${{ inputs.no-verify }}
        INPUT_RESOLVE-VERSIONS: ${{ inputs.resolve-versions }}
