[package]
name = "cli"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "publish-crates-cli"
path = "src/main.rs"

[dependencies]
publish-crates = { path = "../" }
clap = { version = "3", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
