name: release

on: [push, pull_request]
# on:
#   push:
#     tags:
#       - "*"

# i686-pc-windows-gnu,
# i686-pc-windows-msvc,
# x86_64-pc-windows-gnu,
# x86_64-pc-windows-msvc,
# windows-latest

jobs:
  release-binaries:
    runs-on: ${{ matrix.target.os }}
    name: build release (${{ matrix.target.arch }})
    strategy: 
      fail-fast: false
      matrix:
        target:
          - os: ubuntu-latest
            arch: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            arch: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            arch: armv7-unknown-linux-gnueabihf
          - os: ubuntu-latest
            arch: i686-unknown-linux-gnu
          - os: ubuntu-latest
            arch: i686-unknown-linux-musl
          - os: ubuntu-latest
            arch: mips-unknown-linux-gnu
          - os: ubuntu-latest
            arch: mips64-unknown-linux-gnuabi64
          - os: ubuntu-latest
            arch: mips64el-unknown-linux-gnuabi64
          - os: ubuntu-latest
            arch: mipsel-unknown-linux-gnu
          - os: ubuntu-latest
            arch: powerpc-unknown-linux-gnu
          - os: ubuntu-latest
            arch: powerpc64-unknown-linux-gnu
          - os: ubuntu-latest
            arch: powerpc64le-unknown-linux-gnu
          - os: ubuntu-latest
            arch: arm-unknown-linux-gnueabi
          - os: ubuntu-latest
            arch: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            arch: x86_64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v3
      - id: query
        uses: romnn/query-git-action@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target.arch }}

      - name: Compile binaries
        run: >-
          cargo build
          --release
          --package action
          --target ${{ matrix.target.arch }}

      - name: Create package dir
        shell: bash
        run: mkdir publish/

      - name: Package
        shell: bash
        run: >-
          tar
          czvf
          ./publish/publish-crates-action-${{ matrix.target }}.tar.gz
          ./target/${{ matrix.target }}/release/publish-crates-action

      - name: List package dir
        shell: bash
        run: ls -lia ./publish

      - name: Upload release binaries
        if: false
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: publish/*
          tag: ${{ steps.query.outputs.stable_semver_version }}
          release_name: ${{ steps.query.outputs.stable_semver_version }}
          overwrite: true
          file_glob: true
