name: release

on: [push, pull_request]
# on:
#   push:
#     tags:
#       - "*"

# i686-pc-windows-gnu,
# i686-pc-windows-msvc,
# x86_64-pc-windows-gnu,
# x86_64-pc-windows-msvc,
# windows-latest

jobs:
  release-binaries:
    runs-on: ${{ matrix.target.os }}
    name: build release (${{ matrix.target.arch }})
    strategy: 
      fail-fast: false
      matrix:
        target:
          # linux aarch64 
          - os: ubuntu-latest
            arch: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            arch: aarch64-unknown-linux-musl
          # linux armv7
          - os: ubuntu-latest
            arch: armv7-unknown-linux-musleabihf
            # arch: armv7-unknown-linux-gnueabihf
          # linux i686
          - os: ubuntu-latest
            arch: i686-unknown-linux-gnu
          - os: ubuntu-latest
            arch: i686-unknown-linux-musl
          # - os: ubuntu-latest
          #   arch: mips-unknown-linux-gnu
          # - os: ubuntu-latest
          #   arch: mips64-unknown-linux-gnuabi64
          # - os: ubuntu-latest
          #   arch: mips64el-unknown-linux-gnuabi64
          # linux mips
          # - os: ubuntu-latest
          #   arch: mipsel-unknown-linux-gnu
          # - os: ubuntu-latest
          #   arch: powerpc-unknown-linux-gnu
          # - os: ubuntu-latest
          #   arch: powerpc64-unknown-linux-gnu
          # - os: ubuntu-latest
          #   arch: powerpc64le-unknown-linux-gnu
          # linux arm
          - os: ubuntu-latest
            arch: arm-unknown-linux-gnueabi
          - os: ubuntu-latest
            arch: arm-unknown-linux-gnueabihf
          # linux x86
          - os: ubuntu-latest
            arch: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            arch: x86_64-unknown-linux-musl
          # apple  
          - os: macos-latest
            arch: x86_64-apple-darwin
          - os: macos-latest
            arch: aarch64-apple-darwin
          # windows
          - os: windows-latest
            arch: x86_64-pc-windows-gnu
          # # apple  
          # - os: ubuntu-latest
          #   arch: x86_64-apple-darwin
          # - os: ubuntu-latest
          #   arch: aarch64-apple-darwin
          # # windows
          # - os: ubuntu-latest
          #   arch: i686-pc-windows-msvc
          # - os: ubuntu-latest
          #   arch: aarch64-pc-windows-msvc
          # - os: ubuntu-latest
          #   arch: x86_64-pc-windows-gnu
          # - os: ubuntu-latest
          #   arch: x86_64-pc-windows-msvc


    steps:
      - uses: actions/checkout@v3
      - id: query
        uses: romnn/query-git-action@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target.arch }}

      # - name: Install build dependencies
      #   run: sudo apt-get install -y musl-gcc

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ contains(matrix.target.os, 'ubuntu') }}
          command: build
          args: >-
            --release
            --package action
            --target ${{ matrix.target.arch }}

      # - name: Compile binaries
      #   run: >-
      #     cargo build
      #     --release
      #     --package action
      #     --target ${{ matrix.target.arch }}

      - name: Create package dir
        shell: bash
        run: mkdir publish/

      - name: Package
        shell: bash
        run: >-
          tar
          czvf
          ./publish/publish-crates-action-${{ matrix.target.arch }}.tar.gz
          ./target/${{ matrix.target.arch }}/release/publish-crates-action

      - name: List package dir
        shell: bash
        run: ls -lia ./publish

      - name: Upload release binaries
        if: false
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: publish/*
          tag: ${{ steps.query.outputs.stable_semver_version }}
          release_name: ${{ steps.query.outputs.stable_semver_version }}
          overwrite: true
          file_glob: true
