name: release
on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  tests:
    uses: ./.github/workflows/test.yaml

  publish-crate:
    runs-on: ubuntu-24.04
    needs: [tests]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      # publish ourselves
      - name: Publish
        run: cargo run -p cargo-publish-crates
        env:
          REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          RESOLVE_VERSIONS: true
          PUBLISH_DELAY: 30s

  release:
    runs-on: ubuntu-24.04
    needs: [tests]
    outputs:
      precompiled-binaries-url: ${{ steps.upload.outputs.artifact-url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        run: task release
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          TAP_GITHUB_TOKEN: "${{ secrets.TAP_GITHUB_TOKEN }}"
      - name: Upload precompiled binaries
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: goreleaser-dist
          path: goreleaser-dist

  publish-container:
    runs-on: ubuntu-24.04
    needs: [release]
    steps:
      - uses: actions/checkout@v4
      - name: Download precompiled binaries
        uses: actions/download-artifact@v4
        with:
          name: goreleaser-dist
          path: goreleaser-dist
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push multi-arch container
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/romnn/publish-crates:latest
            ghcr.io/romnn/publish-crates:${{ github.ref_name }}
