# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: test action
on:
  push: {}
  pull_request:
    types: [opened, synchronize, reopened, edited]
  schedule:
    # 8AM first day of the month in JAN and JUNE to keep workflow badges up-to-date
    - cron: "0 8 1 1,6 *"

jobs:
  test-action:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Exercise the action
        uses: ./
        with:
          dry-run: true
          resolve-versions: true
