name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
    
      - name: Test
        run: cargo test --workspace --all-targets

      - name: Lint
        continue-on-error: true
        run: >-
          cargo clippy
          --workspace
          --tests
          --benches
          --examples
          -- -Dclippy::all -Dclippy::pedantic

      # publish ourselves
      - name: Publish (dry-run)
        run: cargo run -p publish-crates-action
        env:
          INPUT_TOKEN: ${{ github.token }}
          INPUT_VERSION: latest
          INPUT_NO-VERIFY: true
          INPUT_RESOLVE-VERSIONS: true
          INPUT_DRY-RUN: true
        
      # publish ourselves
      - name: Publish (dry-run)
        run: cargo run -p cargo-publish-crates
        env:
          RESOLVE-VERSIONS: true
          DRY-RUN: true
          NO-VERIFY: true
